# OC-AI Configuration File

# OpenAI Settings
# ---------------
# Your OpenAI API key. Can also be set via OPENAI_API_KEY environment variable
openai_key: "sk-your-api-key-here"

# AI model to use for command generation
# Options: gpt-4-turbo (recommended), gpt-3.5-turbo
default_model: "gpt-4-turbo"

# Command Execution Settings
# ------------------------
# Whether to always confirm command execution, regardless of safety level
confirm_execute: true

# Maximum number of commands to keep in history
history_limit: 100

# CLI Settings
# -----------
# Preferred CLI tool. Options: "oc", "kubectl", or "auto" (default)
# "auto" will use OpenShift CLI (oc) if available, falling back to kubectl
preferred_cli: "auto"

# Safety Settings
# --------------
# Minimum safety level that requires confirmation (1-5)
# 1 = Safe (read-only)
# 2 = Low risk
# 3 = Medium risk (default)
# 4 = High risk
# 5 = Critical (destructive)
min_safety_confirm: 3 